<a href="https://colab.research.google.com/github/Alxzndrn/Assignment-4/blob/main/Assignment4_Calalang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Assignment 4

## What is Matrices?
### A matrix is a rectangular arrays of numbers, symbols, or expressions, arranged in rows and columns.

#### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Activity

### Task 1
Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>

> Indented block


3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

### Function Area

In [ ]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

### Matrix declaration

In [ ]:
## Null Matrix
null_mat = np.array([])

In [ ]:
## Zero Matrix
zero_mat_sqr = np.zeros((3,3))

In [ ]:
## Ones Matrix
ones_mat_sqr = np.ones((3,3))

In [ ]:
## Diagonal Matrix
A = np.array([
    [3, 0, 0],
    [0, 3, 0],
    [0, 0, 9]
])

In [ ]:
## Identity Matrix
# np.identity(3)


In [ ]:
## Upper Triangular Matrix
B = np.array([
    [1, 8, 1],
    [0, 4, 7],
    [0, 0, 9]
])

In [ ]:
#Lower Triangular Matrix
C = np.array([
    [2, 0, 0],
    [6, 4, 0],
    [7, 7, 1]
])

### Test Areas

In [ ]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [ ]:
## Zero Matrix
desc_mat(zero_mat_sqr)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Diagonal Matrix
desc_mat(A)

Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Upper Triangular Matrix
desc_mat(B)

Matrix:
[[1 8 1]
 [0 4 7]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



In [ ]:
#Lower Triangular Matrix
desc_mat(C)

Matrix:
[[2 0 0]
 [6 4 0]
 [7 7 1]]

Shape:	(3, 3)
Rank:	2



### Task 2
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

## Function area

In [ ]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## Matrix declarations

In [ ]:
## Addition
A = np.array([
    [3,1,9],
    [2,0,7],
    [7,1,7]
])
B = np.array([
    [3,2,3],
    [0,4,0],
    [1,1,1]
])

In [ ]:
## Subtraction
D = np.array([
    [4,1,1],
    [3,5,5],
    [0,7,0]
])
E = np.array([
    [9,2,6],
    [9,1,0],
    [0,0,6]
])

In [ ]:
## element-wise multiplication
F = np.array([
    [2,2,2],
    [4,3,4],
    [5,7,7]
])
G = np.array([
    [3,3,3],
    [0,1,9],
    [0,0,6]
])

In [ ]:
## element-wise division
H = np.array([
    [10,12,21],
    [15,9,0],
    [20,22,11]
])
I = np.array([
    [2,6,7],
    [5,3,1],
    [10,11,1]
])

## Test Areas

In [ ]:
## Addition
C = A + B
mat_operations(C)

Matrix:
[[ 4  8  1]
 [ 0  7  7]
 [ 0  0 18]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.add(A,B)

array([[ 4,  8,  1],
       [ 0,  7,  7],
       [ 0,  0, 18]])

In [ ]:
## Subtraction
S = D - E
mat_operations(S)

Matrix:
[[-5 -1 -5]
 [-6  4  5]
 [ 0  7 -6]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.subtract(D,E)

array([[-5, -1, -5],
       [-6,  4,  5],
       [ 0,  7, -6]])

In [ ]:
## element-wise multiplication
M = F*G
mat_operations(M)

Matrix:
[[ 6  6  6]
 [ 0  3 36]
 [ 0  0 42]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.multiply(G,F)

array([[ 6,  6,  6],
       [ 0,  3, 36],
       [ 0,  0, 42]])

In [ ]:
3*F

array([[ 6,  6,  6],
       [12,  9, 12],
       [15, 21, 21]])

In [ ]:
6*G

array([[18, 18, 18],
       [ 0,  6, 54],
       [ 0,  0, 36]])

In [ ]:
## element-wise division
V = H/I
mat_operations(V)

Matrix:
[[ 5.  2.  3.]
 [ 3.  3.  0.]
 [ 2.  2. 11.]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.divide(H,I)

array([[ 5.,  2.,  3.],
       [ 3.,  3.,  0.],
       [ 2.,  2., 11.]])

In [ ]:
H/7

array([[1.42857143, 1.71428571, 3.        ],
       [2.14285714, 1.28571429, 0.        ],
       [2.85714286, 3.14285714, 1.57142857]])

In [ ]:
8/I

array([[4.        , 1.33333333, 1.14285714],
       [1.6       , 2.66666667, 8.        ],
       [0.8       , 0.72727273, 8.        ]])

# Conclusion

As a result, I conclude that we can manipulate and use matrices and their various categories and elements in python and programming to obtain various types of elemental values and linear combinations, which we can then use to compute various matrix algebraic solutions such as addition and even element wise multiplication. Matrix operations can aid in a variety of ways with today's technology and innovation. One of the applications of fpr matrices is to model and optimize wireless transmissions. Extraction and processing of information encoded in signals matrices are utilized for detection. Matrices are important in signal estimation and analysis.

### Reference
[1] Introduction to Matrices https://courses.lumenlearning.com/boundless-algebra/chapter/introduction-to-matrices/
